---
name: Basic checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-24.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Install flake dependencies
        run: nix develop -c echo installed
      - name: Init dev environment
        run: nix develop -c just init
      - name: Check formatting
        run: nix develop -c just format-check
      - name: Check lint
        run: nix develop -c just lint
